# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.swiftyper.com
title: 小锅的 Wiki
keywords: wiki, iOS, Linux, MacOS
description: 小锅的个人 Wiki，专注于 iOS 应用
author: 小锅
theme: simple2

category: 
  - name: iOS
    label: iOS 
  - name: Xcode
    label: Xcode
  - name: iPhone
    label: iPhone
  - name: Linux
    label: Linux
  - name: MacOS
    label: MacOS

markdown:
  - fenced_code
  - extra
  - codehilite(css_class=hlcode, linenum=False)
  - toc(title=Table of Contents)

deploy:
  - type: git
    remote: origin
    branch: master
